CREATE OR REPLACE PROCEDURE CAMERACLAIM
(
  camera_id IN VARCHAR2 
, PATRONID IN VARCHAR2
, STARTTIME TIMESTAMP,
  result OUT NUMBER
)
IS 
BEGIN
  result:=0;
  IF (LOCALTIMESTAMP - STARTTIME <= '+000000000 01:00:00.000000000') THEN
    result := 1;
    UPDATE camera_CHECKOUT SET CLAIMED = 'YES'
    WHERE resource_id = camera_id
    AND P_ID = PATRONID
    AND CHECKOUTDATE = STARTTIME;
  END IF;
END CAMERACLAIM;
