create or replace PROCEDURE ROOMCLAIM 
(
  ROOMNO IN VARCHAR2 
, PATRONID IN VARCHAR2
, STARTTIME TIMESTAMP,
  result OUT NUMBER
)
IS 
BEGIN
  IF (LOCALTIMESTAMP - STARTTIME <= '+000000000 01:00:00.000000000') THEN
    result := 1;
    UPDATE ROOM_CHECKOUT SET ROOMCLAIMED = 'YES'
    WHERE ROOM_NO = roomno
    AND P_ID = PATRONID
    AND CHECKOUTTIME = STARTTIME;
    --DBMS_OUTPUT.PUT_LINE('ROOM CLAIMED');
  END IF;
END ROOMCLAIM;