
package librarymanagement;

import java.awt.event.ActionEvent;
import javax.swing.JPanel;


public class FacultyHome extends javax.swing.JFrame {
        public LoginDAO profile;
	public ProfileDisplay p;
	private JPanel contentPane;
        
    public FacultyHome() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profil = new javax.swing.JButton();
        checked_out_resources = new javax.swing.JButton();
        resources = new javax.swing.JButton();
        due_balance = new javax.swing.JButton();
        resource_request = new javax.swing.JButton();
        notifications = new javax.swing.JButton();
        reserved_books = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profil.setLabel("Profile");
        profil.setName(""); // NOI18N
        profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilActionPerformed(evt);
            }
        });

        checked_out_resources.setText("Checked-Out Resources");
        checked_out_resources.setName("checked_out_resources"); // NOI18N
        checked_out_resources.setOpaque(false);
        checked_out_resources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checked_out_resourcesActionPerformed(evt);
            }
        });

        resources.setText("Resources");
        resources.setName("resources"); // NOI18N
        resources.setOpaque(false);
        resources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesActionPerformed(evt);
            }
        });

        due_balance.setText("Due Balance");
        due_balance.setName("due_balance"); // NOI18N
        due_balance.setOpaque(false);
        due_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                due_balanceActionPerformed(evt);
            }
        });

        resource_request.setText("Resource-Request");
        resource_request.setName("resource_request"); // NOI18N
        resource_request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resource_requestActionPerformed(evt);
            }
        });

        notifications.setText("Notifications");
        notifications.setName("notifications"); // NOI18N
        notifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationsActionPerformed(evt);
            }
        });

        reserved_books.setText("Reserved Books");
        reserved_books.setName("reserved_books"); // NOI18N
        reserved_books.setOpaque(false);
        reserved_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserved_booksActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.setName("logout"); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reserved_books, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resource_request, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(resources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(due_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checked_out_resources)
                    .addComponent(notifications, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profil)
                    .addComponent(checked_out_resources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resources)
                    .addComponent(due_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resource_request)
                    .addComponent(notifications, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(reserved_books)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String string;

    /**
     * Get the value of string
     *
     * @return the value of string
     */
    public String getString() {
        return string;
    }

    /**
     * Set the value of string
     *
     * @param string new value of string
     */
    public void setString(String string) {
        this.string = string;
    }

    private void profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilActionPerformed

    private void due_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_due_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_due_balanceActionPerformed

    private void resource_requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resource_requestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resource_requestActionPerformed

    private void reserved_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserved_booksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserved_booksActionPerformed

    private void checked_out_resourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checked_out_resourcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checked_out_resourcesActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

				FacultyLogin j =new FacultyLogin();
				setVisible(false);
				j.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void notificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationsActionPerformed

    private void resourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resourcesActionPerformed

   /* private void jButton8ActionPerformed(java.awt.event.ActionEvent evt){
				FacultyLogin s = new FacultyLogin();
				setVisible(false);
				s.setVisible(true);
			}
    }
    /**
     * @param args the command line arguments
     */     
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checked_out_resources;
    private javax.swing.JButton due_balance;
    private javax.swing.JButton logout;
    private javax.swing.JButton notifications;
    private javax.swing.JButton profil;
    private javax.swing.JButton reserved_books;
    private javax.swing.JButton resource_request;
    private javax.swing.JButton resources;
    // End of variables declaration//GEN-END:variables
}
