create or replace PROCEDURE ROOMBOOKPROC (
  roomno VARCHAR2,
  patronId VARCHAR2,
  STARTTIME IN TIMESTAMP, 
  ENDTIME IN TIMESTAMP)
IS
  OUTTIME1 TIMESTAMP;
  INTIME1 TIMESTAMP;
  OUTTIME2 TIMESTAMP;
  INTIME2 TIMESTAMP;
  LID NUMBER;
BEGIN
  SELECT L_ID INTO LID FROM ROOMS WHERE ROOM_NO = ROOMNO;
  SELECT MAX(CHECKOUTTIME), MAX(RETURNTIME) INTO OUTTIME1, INTIME1 FROM ROOM_CHECKOUT
  WHERE  CHECKOUTTIME <=STARTTIME
  AND ROOM_NO=ROOMNO;
  SELECT MIN(CHECKOUTTIME), MIN(RETURNTIME) INTO OUTTIME2, INTIME2 FROM ROOM_CHECKOUT
  WHERE CHECKOUTTIME >= STARTTIME
  AND ROOM_NO=ROOMNO;
  IF ((INTIME1 <= STARTTIME) OR (OUTTIME1 IS NULL)) THEN
    IF ((OUTTIME2 >= ENDTIME) OR (OUTTIME2 IS NULL)) THEN
      IF(ENDTIME - STARTTIME <= '+000000000 03:00:00.000000000') THEN
        DBMS_OUTPUT.PUT_LINE('ROOM BOOKED');
        INSERT INTO ROOM_CHECKOUT(ROOM_NO, L_ID, CHECKOUTTIME, RETURNTIME, P_ID) VALUES (ROOMNO, LID, STARTTIME, ENDTIME, PATRONID);
      ELSE
        DBMS_OUTPUT.PUT_LINE('NOT ALLOWED TO BOOK');
      END IF;
    ELSE
      DBMS_OUTPUT.PUT_LINE('NOT ALLOWED TO BOOK');
    END IF;
  ELSE
    DBMS_OUTPUT.PUT_LINE('NOT ALLOWED TO BOOK');
  END IF;
END ROOMBOOKPROC;