create or replace PROCEDURE ROOMCLAIM 
(
  ROOMNO IN VARCHAR2 
, PATRONID IN VARCHAR2
, STARTTIME TIMESTAMP
)
IS 
BEGIN
  UPDATE ROOM_CHECKOUT SET ROOMCLAIMED = 'YES'
  WHERE ROOM_NO = roomno
  AND P_ID = PATRONID
  AND CHECKOUTTIME = STARTTIME;
  DBMS_OUTPUT.PUT_LINE('ROOM CLAIMED');
END ROOMCLAIM;